name = "TraitWrapper"
uuid = "ef569cd2-5787-430a-a8c5-986931a3f6a1"
authors = ["evalparse <zhuojia.dai@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
